name: Lint new or modified files using Super Linter

on: push

jobs:
  build:
    name: Run Tests Across Node.js Versions and Operating Systems
    runs-on: windows-latest
    
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 8
      - uses: actions/checkout@v4
      - name: Run TestCafe Tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome ../../testrunner.js"
